global:
  scrape_interval:     15s
  external_labels:
    monitor: 'iota-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [${node_exporter}]
  - job_name: 'hornet_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [${hornet_exporter}]