{
 "title": "Hornet Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "health_nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iota_node_health{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_node_app_info{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "hornet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "node_health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "iota_node_health{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "node_milestones",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "iota_node_milestones{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "caches_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "iota_caches_size{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "MPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iota_node_messages_per_second{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "request_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "iota_node_request_count{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "tangle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "RECEIVED MESSAGES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_message_count{instance=\"$node\",job=\"$job\",type=\"known\"}"
    }
   ]
  },
  {
   "title": "NEW MESSAGES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_message_count{instance=\"$node\",job=\"$job\",type=\"new\"}"
    }
   ]
  },
  {
   "title": "RECEIVED MESSAGES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_message_count{instance=\"$node\",job=\"$job\",type=\"all\"}"
    }
   ]
  },
  {
   "title": "SENT MESSAGES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_message_count{instance=\"$node\",job=\"$job\",type=\"sent\"}"
    }
   ]
  },
  {
   "title": "RECEIVED MESSAGE REQUESTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_request_count{instance=\"$node\",job=\"$job\",type=\"received_message\"}"
    }
   ]
  },
  {
   "title": "SENT MESSAGE REQUESTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_request_count{instance=\"$node\",job=\"$job\",type=\"sent_message\"}"
    }
   ]
  },
  {
   "title": "RECEIVED HEARTBEATS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_heartbeat_count{instance=\"$node\",job=\"$job\",type=\"received\"}"
    }
   ]
  },
  {
   "title": "SENT HEARTBEATS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_heartbeat_count{instance=\"$node\",job=\"$job\",type=\"sent\"}"
    }
   ]
  },
  {
   "title": "RECEIVED MILESTONE REQUESTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_request_count{instance=\"$node\",job=\"$job\",type=\"received_milestone\"}"
    }
   ]
  },
  {
   "title": "SENT MILESTONE REQUESTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_request_count{instance=\"$node\",job=\"$job\",type=\"sent_milestone\"}"
    }
   ]
  },
  {
   "title": "DROPPED PACKETS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_gossip_node_dropped_count{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "iota_database_tangle_compaction_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "iota_database_tangle_compaction_count{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "iota_database_tangle_compaction_running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "iota_database_tangle_compaction_running{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "iota_database_tangle_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "iota_database_tangle_size_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  }
 ]
}